### PR TITLE
Replace vatnumber by stdnum

### PR DESCRIPTION
**Pull request by PetrDlouhy**
This is almost the same as #153, but uses `python-stdnum`, which was used by `vatnumber`. The main difference is, that `python-stdnum` raises exceptions when the VIES check fails, so the errors are logged same way as with `vatnumber` (for which I made at least some test).

This doesn't contain the Greek tax fix, for which I will rebase and re-open the PR #150 into new PR #155.

### CODE REVIEW

**Comment by Alir3z4** [comment]
@PetrDlouhy could you please fix the merge conflicts so I can merge this?

**Comment by PetrDlouhy** [comment]
@Alir3z4 Done.

**Comment by Alir3z4** [comment]
Still merge conflicts.

**Comment by PetrDlouhy** [comment]
@Alir3z4 Changes here were already part of #155, so there is nothing left to do here. I am closing this.

**Pull request closed without merging**
