### PR TITLE
Default billing info country from ip

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by Alir3z4** [comment]
@PetrDlouhy can you please fix the merge conflicts so I can merge this quick ?

**Comment by PetrDlouhy** [comment]
@Alir3z4 Sorry, I forgot about this. Now it is rebased.

**Comment by Alir3z4** [comment]
This would be great to be an optional dependencies and also a setting variable flag to enable/disable it.

**Comment by PetrDlouhy** [comment]
@Alir3z4 The dependency was optional even in the original PR. Now I have added configuration variables, that manages this. The default configuration should be identical with `django-plans` current behavior.

**Pull request merged**
