### PR TITLE
[#85] Added Abstract / Swappable models

### PR DESCRIPTION
**Pull request by nemesisdesign**
Refers to #85 .

### CODE REVIEW

**Comment by Alir3z4** [comment]
This is great, thank you for making this happen!

Could you please add documentation for this as well ?
Without having some documentation and use case, I'm not sure if users will be able to use it.

**Comment by nemesisdesign** [comment]
@Alir3z4 sure, I had written some docs but forgot to push. Pushed now. However, it's very basics, maybe I could expand but I'm not sure where is best to place the explanation, could you give me a hint please?

I see there's a conflict, I need to fix that as well.

**Comment by Alir3z4** [comment]
I would say it would be good to have a section in https://django-plans.readthedocs.io/en/latest/settings.html so User know where to swap the models.

Then it would be good to have a dedicated page for it in https://github.com/django-getpaid/django-plans/tree/master/docs/source as well and [shown on the navigation bar](https://github.com/django-getpaid/django-plans/blob/master/docs/source/index.rst#contents) when the docs are built.

It worth nothing on the readme.md as well

**Comment by nemesisdesign** [comment]
@Alir3z4 thanks for the guidance, I will work on it in the next days and ping you when ready

**Comment by nemesisdesign** [comment]
I'm sorry I couldn't complete this PR.
I made a note to finish this asap.

**Comment by nemesisdesign** [comment]
@Alir3z4 let's continue in https://github.com/django-getpaid/django-plans/pull/126

**Pull request closed without merging**
