### PR TITLE
Added pending migrations

### PR DESCRIPTION
**Pull request by pandafy**
Added test in CI build to avoid merging of code without migrations.

### CODE REVIEW

**Comment by Alir3z4** [comment]
This is a good catch.

**Comment by Alir3z4** [comment]
@pandafy could you please resolve the merge conflicts?

**Review by Alir3z4 — APPROVED** [review]

**Comment by Alir3z4** [comment]
Still merge conflicts.

Seems I've merged the other ones caused this to be in conflict again.

**Comment by pandafy** [comment]
@Alir3z4 I have rebased again. 😄

**Comment by PetrDlouhy** [comment]
@Alir3z4 Could you please approve the tests to run?

**Comment by Alir3z4** [comment]
Sorry, I've missed the request to run the CI.

I've ran it and seems all the tests fail.

**Comment by PetrDlouhy** [comment]
The tests are probably failing because the VIES service was in some kind of error. The same commit is in #159, and the tests did run OK. Restarting them should help.

**Comment by Alir3z4** [comment]
OK, rerunning them now.

**Comment by Alir3z4** [comment]
You're correct, all passing.
Merging now.

**Pull request merged**
