### PR TITLE
use test service for testing VIES to make testing more robust

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Tests failed sometimes when many of them ran at the same time, because VIES service is very unreliable.
Hope would be fixed with usage of VIES testing service and VIES testing numbers.

### CODE REVIEW

**Review by nemesisdesign — COMMENTED** [review]
In my experience, for testing it's better to use mocking.
Two good options are the [responses library](https://github.com/getsentry/responses) (mocks responses from requests library) and [cassette](https://github.com/uber/cassette).

Responses should be easy to use for this single test, but we can do so only if the HTTP requests are made through the requests library, is that so?

In short, these testing utilities help to store a record of the response from the prod service, and replicate it during testing, like if it was prod, but without hitting the network.

**Comment by Alir3z4** [comment]
@PetrDlouhy is it actually making http/web requests to some API?
if that's the case, I believe best would be to have them all mocked as @nemesisdesign mentioned.

A simple network error could cripple the whole CI or any tests which is pretty common for CI environments.

**Review by nemesisdesign — COMMENTED** [review]
https://github.com/django-getpaid/django-plans/pull/174 merged, please can you rebase this branch and fix conflicts?

**Comment by PetrDlouhy** [comment]
I think this is superseeded by #174, I am closing this.

**Pull request closed without merging**
